/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Alert Rules */
        get: operations["api_alert_rules_v1_alert_rules_get"];
        put?: never;
        /** Api Create Alert Rule */
        post: operations["api_create_alert_rule_v1_alert_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Alerts */
        get: operations["api_alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Acknowledge Alert */
        post: operations["api_acknowledge_alert_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Assets */
        get: operations["api_assets_v1_assets_get"];
        put?: never;
        /** Api Create Asset */
        post: operations["api_create_asset_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Asset */
        get: operations["api_asset_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        /** Api Delete Asset */
        delete: operations["api_delete_asset_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api List Events */
        get: operations["api_list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Event Detail */
        get: operations["api_event_detail_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/impacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Event Impacts */
        get: operations["api_event_impacts_v1_events__event_id__impacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Event Observations */
        get: operations["api_event_observations_v1_events__event_id__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Event Revisions */
        get: operations["api_event_revisions_v1_events__event_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Event Timeline */
        get: operations["api_event_timeline_v1_events__event_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Operations Summary */
        get: operations["api_operations_summary_v1_operations_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Source Runs */
        get: operations["api_source_runs_v1_source_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Sources */
        get: operations["api_sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Sources Health */
        get: operations["api_sources_health_v1_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Asset Id */
            asset_id: string;
            /** Asset Name */
            asset_name: string;
            /** Created At */
            created_at?: string | null;
            /** Deduplication Key */
            deduplication_key: string;
            /** Distance M */
            distance_m: number;
            /** Event Id */
            event_id: string;
            /** Event Title */
            event_title: string;
            /** Id */
            id: string;
            /** Impact Id */
            impact_id: string;
            /** Message */
            message: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Rule Id */
            rule_id: string;
            /** Status */
            status: string;
        };
        /** AlertRule */
        AlertRule: {
            /** Asset Id */
            asset_id: string;
            /** Cooldown Minutes */
            cooldown_minutes: number;
            /** Created At */
            created_at?: string | null;
            /** Distance Threshold M */
            distance_threshold_m: number;
            /** Enabled */
            enabled: boolean;
            /** Event Type */
            event_type: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AlertRuleCreate */
        AlertRuleCreate: {
            /** Asset Id */
            asset_id: string;
            /**
             * Cooldown Minutes
             * @default 0
             */
            cooldown_minutes: number;
            /** Distance Threshold M */
            distance_threshold_m: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Event Type
             * @default wildfire
             */
            event_type: string;
            /** Name */
            name: string;
        };
        /** Asset */
        Asset: {
            /** Asset Type */
            asset_type: string;
            /** Created At */
            created_at?: string | null;
            /** Criticality */
            criticality: string;
            /** Id */
            id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AssetCreate */
        AssetCreate: {
            /**
             * Asset Type
             * @default site
             */
            asset_type: string;
            /**
             * Criticality
             * @default normal
             */
            criticality: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
        };
        /** EventDetailFeature */
        EventDetailFeature: {
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["EventDetailProperties"];
            /** Type */
            type: string;
        };
        /** EventDetailProperties */
        EventDetailProperties: {
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Impacts Count */
            impacts_count?: number | null;
            /** Last Observed At */
            last_observed_at?: string | null;
            /** Observations Count */
            observations_count?: number | null;
            /** Precision M */
            precision_m?: number | null;
            /** Revisions Count */
            revisions_count?: number | null;
            /** Severity */
            severity?: string | null;
            /** Severity Source Id */
            severity_source_id?: string | null;
            /** Sources */
            sources: string[];
            /** Status */
            status?: string | null;
            /** Status Source Id */
            status_source_id?: string | null;
            /** Subtype */
            subtype?: string | null;
            /** Summary */
            summary?: string | null;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Updated At */
            updated_at?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** EventFeature */
        EventFeature: {
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["EventProperties"];
            /** Type */
            type: string;
        };
        /** EventFeatureCollection */
        EventFeatureCollection: {
            /** Features */
            features: components["schemas"]["EventFeature"][];
            meta: components["schemas"]["FeatureCollectionMeta"];
            /** Type */
            type: string;
        };
        /** EventProperties */
        EventProperties: {
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Last Observed At */
            last_observed_at?: string | null;
            /** Precision M */
            precision_m?: number | null;
            /** Severity */
            severity?: string | null;
            /** Severity Source Id */
            severity_source_id?: string | null;
            /** Sources */
            sources: string[];
            /** Status */
            status?: string | null;
            /** Status Source Id */
            status_source_id?: string | null;
            /** Subtype */
            subtype?: string | null;
            /** Summary */
            summary?: string | null;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Updated At */
            updated_at?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** EventTimeline */
        EventTimeline: {
            /** Event Id */
            event_id: string;
            /** Generated At */
            generated_at?: string | null;
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** FeatureCollectionMeta */
        FeatureCollectionMeta: {
            /** Generated At */
            generated_at?: string | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Partial */
            partial: boolean;
            /** Total Matched */
            total_matched: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** Impact */
        Impact: {
            /** Asset Id */
            asset_id: string;
            /** Asset Name */
            asset_name: string;
            /** Calculated At */
            calculated_at?: string | null;
            /** Calculation Version */
            calculation_version: string;
            /** Distance M */
            distance_m: number;
            /** Event Id */
            event_id: string;
            /** Id */
            id: string;
            /** Impact Type */
            impact_type: string;
            /** Intersects */
            intersects: boolean;
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** ManifestState */
        ManifestState: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Data Age Seconds */
            data_age_seconds: {
                [key: string]: number;
            };
            /** Degraded */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
            /** Demo */
            demo: boolean;
            /** Demo Reason */
            demo_reason?: string | null;
            /** Frp Total Mw */
            frp_total_mw?: number | null;
            /** Generated At */
            generated_at?: string | null;
            /** Pipeline Age Seconds */
            pipeline_age_seconds?: number | null;
            /** Worst Data Age Seconds */
            worst_data_age_seconds?: number | null;
        };
        /** Observation */
        Observation: {
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: number | null;
            /** Event Type */
            event_type: string;
            geometry: components["schemas"]["PointGeometry"];
            /** Id */
            id: string;
            /** Ingested At */
            ingested_at?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Precision M */
            precision_m?: number | null;
            /** Published At */
            published_at?: string | null;
            /** Reconciliation Version */
            reconciliation_version: string;
            /** Relation Type */
            relation_type: string;
            /** Source Id */
            source_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Source Version */
            source_version: string;
        };
        /** OperationsSummary */
        OperationsSummary: {
            /** Assets Total */
            assets_total: number;
            /** Events By Source */
            events_by_source: {
                [key: string]: number;
            };
            /** Events By Status */
            events_by_status: {
                [key: string]: number;
            };
            /** Events By Type */
            events_by_type: {
                [key: string]: number;
            };
            /** Events Recent 24H */
            events_recent_24h: number;
            /** Events Total */
            events_total: number;
            /** Events With Impact */
            events_with_impact: number;
            /** Generated At */
            generated_at?: string | null;
            /** Latest Ingested At */
            latest_ingested_at?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            manifest: components["schemas"]["ManifestState"];
            /** Open Alerts */
            open_alerts: number;
            source_health: components["schemas"]["SummarySourceHealth"];
            /** Sources Degraded */
            sources_degraded: string[];
            /** Sources Total */
            sources_total: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ];
            /** Type */
            type: string;
        };
        /** ReadyStatus */
        ReadyStatus: {
            /** Dependency */
            dependency: string;
            /** Postgis Version */
            postgis_version: string;
            /** Status */
            status: string;
        };
        /** Revision */
        Revision: {
            /** Changed At */
            changed_at?: string | null;
            /** Changed Fields */
            changed_fields: string[];
            /** Event Id */
            event_id: string;
            /** Id */
            id: string;
            /** New Snapshot */
            new_snapshot: {
                [key: string]: unknown;
            };
            /** Previous Snapshot */
            previous_snapshot: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Revision Number */
            revision_number: number;
            /** Source Observation Ids */
            source_observation_ids: string[];
        };
        /** Source */
        Source: {
            /** Created At */
            created_at?: string | null;
            /** Criticality */
            criticality: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** SourceHealth */
        SourceHealth: {
            /** Consecutive Failures */
            consecutive_failures?: number | null;
            /** Coverage */
            coverage?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Criticality */
            criticality: string;
            /** Data Age Seconds */
            data_age_seconds?: number | null;
            /** Download Age Seconds */
            download_age_seconds?: number | null;
            /** Enabled */
            enabled: boolean;
            /** Error */
            error?: string | null;
            /** Freshness Status */
            freshness_status: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Last Download At */
            last_download_at?: string | null;
            last_run?: components["schemas"]["SourceLastRun"] | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /** Name */
            name: string;
            /** Organism */
            organism?: string | null;
            /** Pipeline Age Seconds */
            pipeline_age_seconds?: number | null;
            /** Precision M */
            precision_m?: number | null;
            /** Records */
            records?: number | null;
            /** Region */
            region?: string | null;
            /** Stale Reason */
            stale_reason?: string | null;
            /** Ttl Seconds */
            ttl_seconds?: number | null;
        };
        /** SourceLastRun */
        SourceLastRun: {
            /** Error Message */
            error_message?: string | null;
            /** Error Type */
            error_type?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /** Records Accepted */
            records_accepted: number;
            /** Records Downloaded */
            records_downloaded: number;
            /** Records Rejected */
            records_rejected: number;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** SourceRun */
        SourceRun: {
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /** Records Accepted */
            records_accepted: number;
            /** Records Downloaded */
            records_downloaded: number;
            /** Records Rejected */
            records_rejected: number;
            /** Source Id */
            source_id: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** SummarySourceHealth */
        SummarySourceHealth: {
            /** Failed Sources */
            failed_sources: string[];
            /** Latest Success At */
            latest_success_at?: string | null;
            /** Stale Sources */
            stale_sources: string[];
            /** Worst Data Age Seconds */
            worst_data_age_seconds?: number | null;
            /** Worst Download Age Seconds */
            worst_download_age_seconds?: number | null;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Changed Fields */
            changed_fields?: string[] | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Precision M */
            precision_m?: number | null;
            /** Source Id */
            source_id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
        };
    };
    api_alert_rules_v1_alert_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"][];
                };
            };
        };
    };
    api_create_alert_rule_v1_alert_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_alerts_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
        };
    };
    api_acknowledge_alert_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_assets_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    api_create_asset_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_asset_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_delete_asset_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_list_events_v1_events_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                types?: string | null;
                from?: string | null;
                to?: string | null;
                updated_after?: string | null;
                status?: string | null;
                sources?: string | null;
                origins?: string | null;
                sensors?: string | null;
                min_confidence?: number | null;
                has_impact?: boolean | null;
                has_alert?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_event_detail_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_event_impacts_v1_events__event_id__impacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Impact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_event_observations_v1_events__event_id__observations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_event_revisions_v1_events__event_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_event_timeline_v1_events__event_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_operations_summary_v1_operations_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsSummary"];
                };
            };
        };
    };
    api_source_runs_v1_source_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRun"][];
                };
            };
        };
    };
    api_sources_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    api_sources_health_v1_sources_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealth"][];
                };
            };
        };
    };
}
